#!/bin/bash

# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.

set -e

cd "$(dirname "$0")/.."

make -C vendor/libopencm3 lib/stm32/f2

# make unemulated bootloader
EMULATOR=0 make
EMULATOR=0 make -C bootloader

if [ "$EMULATOR" = 1 ]; then
    # remake base files
    make -C emulator
    make clean && make
fi

if [ "$FASTFLASH" = 1 ]; then
    make -C fastflash
fi

make -C vendor/nanopb/generator/proto
make -C firmware/protob

make -C firmware
